#[derive(Debug, PartialEq, Clone, Copy)]
pub enum OpCode {
    NOOP,
    CLS,
    RET,
    JP { addr: u16 },
    CALL { addr: u16 },
    SE { vx: u16, other: u16, by_value: bool },
    SNE { vx: u16, other: u16, by_value: bool },
    LD { vx: u16, other: u16, by_value: bool },
    ADD { vx: u16, byte: u16 },
    OR { vx: u16, vy: u16 },
    AND { vx: u16, vy: u16 },
    XOR { vx: u16, vy: u16 },
    ADDREG { vx: u16, vy: u16 },
    SUB { vx: u16, vy: u16 },
    SHR { vx: u16, vy: u16 },
    SUBN { vx: u16, vy: u16 },
    SHL { vx: u16, vy: u16 },
    LDI { addr: u16 },
    JPV0 { addr: u16 },
    RND { vx: u16, byte: u16 },
    DRW { vx: u16, vy: u16, nibble: u16 },
    SKP { vx: u16 },
    SKNP { vx: u16 },
    LDVXDT { vx: u16 },
    LDK { vx: u16 },
    LDDTVX { vx: u16 },
    LDSTVX { vx: u16 },
    ADDI { vx: u16 },
    LDF { vx: u16 },
    LDB { vx: u16 },
    LDMEMI { vx: u16 },
    LDVXMEMI { vx: u16 },
}